import './header.css';

const javalang = [
    {
      id: 1,
     
      name: "abstract",
      
      meaning:
        "“Java abstract keyword is used to declare an abstract class. An abstract class can provide the implementation of the interface. It can have abstract and non-abstract methods.",
      Button_link :<a href="https://www.geeksforgeeks.org/abstract-keyword-in-java/" class="button_lang">click</a>
    },
    {
      id: 2,
      
      name: "boolean",
      meaning:
        "Java boolean keyword is used to declare a variable as a boolean type. It can hold True and False values only.",
        Button_link :<a href="https://www.javatpoint.com/boolean-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 3,
      
      name: "break",
      meaning:
        "Java break keyword is used to break the loop or switch statement. It breaks the current flow of the program at specified conditions",
        Button_link :<a href="https://howtodoinjava.com/java/flow-control/break-keyword/" class="button_lang">click</a>
    },
    {
    id: 4,
      
      name: "byte",
      meaning:
        "Java byte keyword is used to declare a variable that can hold 8-bit data values.",
        Button_link :<a href="https://www.javatpoint.com/byte-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 5,
      
      name: "case",
      meaning:
        "Java case keyword is used with the switch statements to mark blocks of text.",
        Button_link :<a href="https://www.w3schools.com/java/ref_keyword_case.asp" class="button_lang">click</a>
    },
    {
    id: 6,
      
      name: "catch",
      meaning:
        "Java catch keyword is used to catch the exceptions generated by try statements. It must be used after the try block only.",
        Button_link :<a href="https://www.w3schools.com/java/ref_keyword_catch.asp" class="button_lang">click</a>
    },
    {
    id: 7,
      
      name: "char",
      meaning:
        "Java char keyword is used to declare a variable that can hold unsigned 16-bit Unicode characters",
        Button_link :<a href="https://www.softwaretestinghelp.com/java-char-tutorial/" class="button_lang">click</a>
    },
    {
    id: 8,
      
      name: "class",
      meaning:
        "Java class keyword is used to declare a class",
        Button_link :<a href="https://javascript.info/class" class="button_lang">click</a>
    },
    {
    id: 9,
      
      name: "continue",
      meaning:
        "Java continue keyword is used to continue the loop. It continues the current flow of the program and skips the remaining code at the specified condition.",
        Button_link :<a href="https://howtodoinjava.com/tutorials/java-keywords/continue/" class="button_lang">click</a>
    },
    {
    id: 10,
      
      name: "default",
      meaning:
        "Java default keyword is used to specify the default block of code in a switch statement.",
        Button_link :<a href="https://www.javatpoint.com/default-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 11,
      
      name: "do",
      meaning:
        "Java do keyword is used in the control statement to declare a loop. It can iterate a part of the program several times.",
        Button_link :<a href="https://www.w3schools.com/java/ref_keyword_do.asp" class="button_lang">click</a>
    },
    {
    id: 12,
      
      name: "double",
      meaning:
        "Java double keyword is used to declare a variable that can hold 64-bit floating-point number.",
        Button_link :<a href="https://howtodoinjava.com/tutorials/java-keywords/double/" class="button_lang">click</a>
    },
    {
    id: 13,
      
      name: "else",
      meaning:
        "Java else keyword is used to indicate the alternative branches in an if statement.",
        Button_link :<a href="https://howtodoinjava.com/tutorials/java-keywords/else/" class="button_lang">click</a>
    },
    {
    id: 14,
      
      name: "enum",
      meaning:
        "Java enum keyword is used to define a fixed set of constants. Enum constructors are always private or default.",
        Button_link :<a href="https://www.simplilearn.com/tutorials/java-tutorial/enum-in-java" class="button_lang">click</a>
    },
    {
    id: 15,
      
      name: "extends",
      meaning:
        "Java extends keyword is used to indicate that a class is derived from another class or interface.",
        Button_link :<a href="https://www.w3schools.com/java/ref_keyword_extends.asp" class="button_lang">click</a>
    },
    {
    id: 16,
      
      name: "final",
      meaning:
        "Java final keyword is used to indicate that a variable holds a constant value. It is used with a variable. It is used to restrict the user from updating the value of the variable.",
        Button_link :<a href="https://www.javatpoint.com/final-keyword" class="button_lang">click</a>
    },
    {
    id: 17,
      
      name: "finally",
      meaning:
        " Java finally keyword indicates a block of code in a try-catch structure. This block is always executed whether an exception is handled or not.",
        Button_link :<a href="https://www.javatpoint.com/final-keyword" class="button_lang">click</a>
    },
    {
    id: 18,
      
      name: "float",
      meaning:
        "Java float keyword is used to declare a variable that can hold a 32-bit floating-point number.",
        Button_link :<a href="https://www.javatpoint.com/float-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 19,
      
      name: "for",
      meaning:
        "Java for keyword is used to start a for loop. It is used to execute a set of instructions/functions repeatedly when some condition becomes true. If the number of iteration is fixed, it is recommended to use for loop.",
        Button_link :<a href="https://www.w3schools.com/java/java_syntax.asp" class="button_lang">click</a>
    },
    {
    id: 20,
      
      name: "if",
      meaning:
        "Java if keyword tests the condition. It executes the if block if the condition is true.",
        Button_link :<a href="https://www.w3schools.com/java/ref_keyword_if.asp" class="button_lang">click</a>
    },
    {
    id: 21,
      
      name: "implements",
      meaning:
        "Java implements keyword is used to implement an interface.",
        Button_link :<a href="https://www.w3schools.com/java/ref_keyword_implements.asp" class="button_lang">click</a>
    },
    {
    id: 22,
      
      name: "import",
      meaning:
        "Java import keyword makes classes and interfaces available and accessible to the current source code.",
        Button_link :<a href="https://www.geeksforgeeks.org/static-import-java/" class="button_lang">click</a>
    },
    {
    id: 23,
      
      name: "instanceof",
      meaning:
        " Java instanceof keyword is used to test whether the object is an instance of the specified class or implements an interface.",
        Button_link :<a href="https://www.programiz.com/java-programming/instanceof" class="button_lang">click</a>
    },
    {
    id: 24,
      
      name: "int",
      meaning:
        "Java int keyword is used to declare a variable that can hold a 32-bit signed integer.",
        Button_link :<a href="https://www.javatpoint.com/int-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 25,
      
      name: "interface",
      meaning:
        "Java interface keyword is used to declare an interface. It can have only abstract methods.",
        Button_link :<a href="https://www.javatpoint.com/interface-in-java" class="button_lang">click</a>
    },
    {
    id: 26,
      
      name: "long",
      meaning:
        "Java long keyword is used to declare a variable that can hold a 64-bit integer.",
        Button_link :<a href="https://www.codejava.net/java-core/the-java-language/long-keyword" class="button_lang">click</a>
    },
    {
    id: 27,
      
      name: "native",
      meaning:
        "Java native keyword is used to specify that a method is implemented in native code using JNI (Java Native Interface).",
        Button_link :<a href="https://www.educba.com/native-keyword-in-java/" class="button_lang">click</a>
    },
    {
    id: 28,
      
      name: "new",
      meaning:
        " Java new keyword is used to create new objects.",
        Button_link :<a href="https://www.javatpoint.com/new-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 29,
      
      name: "null",
      meaning:
        "Java null keyword is used to indicate that a reference does not refer to anything. It removes the garbage value.",
        Button_link :<a href="https://www.javatpoint.com/null-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 30,
      
      name: "package",
      meaning:
        "Java package keyword is used to declare a Java package that includes the classes.",
        Button_link :<a href="https://www.w3schools.com/java/ref_keyword_package.asp" class="button_lang">click</a>
    },
    {
    id: 31,
      
      name: "private",
      meaning:
        " Java private keyword is an access modifier. It is used to indicate that a method or variable may be accessed only in the class in which it is declared.",
        Button_link :<a href="https://www.javatpoint.com/private-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 32,
      
      name: "protected",
      meaning:
        "Java protected keyword is an access modifier. It can be accessible within the package and outside the package but through inheritance only. It can't be applied with the class.",
        Button_link :<a href="https://www.javatpoint.com/protected-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 33,
      
      name: "public",
      meaning:
        "Java public keyword is an access modifier. It is used to indicate that an item is accessible anywhere. It has the widest scope among all other modifiers.",
        Button_link :<a href="https://www.javatpoint.com/public-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 34,
      
      name: "return",
      meaning:
        "Java return keyword is used to return from a method when its execution is complete.",
        Button_link :<a href="https://www.geeksforgeeks.org/return-keyword-java/" class="button_lang">click</a>
    },
    {
    id: 35,
      
      name: "short",
      meaning:
        " Java short keyword is used to declare a variable that can hold a 16-bit integer.",
        Button_link :<a href="https://www.javatpoint.com/short-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 36,
      
      name: "static",
      meaning:
        "Java static keyword is used to indicate that a variable or method is a class method. The static keyword in Java is mainly used for memory management.",
        Button_link :<a href="https://www.javatpoint.com/static-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 37,
      
      name: "strictfp",
      meaning:
        "Java strictfp is used to restrict the floating-point calculations to ensure portability.",
        Button_link :<a href="https://www.javatpoint.com/strictfp-keyword" class="button_lang">click</a>
    },
    {
    id: 38,
      
      name: "super",
      meaning:
        "Java super keyword is a reference variable that is used to refer to parent class objects. It can be used to invoke the immediate parent class method.",
        Button_link :<a href="https://www.javatpoint.com/super-keyword" class="button_lang">click</a>
    },
    {
    id: 39,
      
      name: "switch",
      meaning:
        " The Java switch keyword contains a switch statement that executes code based on test value. The switch statement tests the equality of a variable against multiple values.",
        Button_link :<a href="https://www.w3schools.com/java/java_switch.asp" class="button_lang">click</a>
    },
    {
    id: 40,
      
      name: "synchronized",
      meaning:
        "Java synchronized keyword is used to specify the critical sections or methods in multithreaded code.",
        Button_link :<a href="https://www.tutorialspoint.com/synchronized-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 41,
      
      name: "this",
      meaning:
        "Java this keyword can be used to refer the current object in a method or constructor.",
        Button_link :<a href="https://www.javatpoint.com/this-keyword" class="button_lang">click</a>
    },
    {
    id: 42,
      
      name: "throw",
      meaning:
        "The Java throw keyword is used to explicitly throw an exception. The throw keyword is mainly used to throw custom exceptions. It is followed by an instance.",
        Button_link :<a href="https://www.javatpoint.com/throw-keyword" class="button_lang">click</a>
    },
    {
    id: 43,
      
      name: "throws",
      meaning:
        "The Java throws keyword is used to declare an exception. Checked exceptions can be propagated with throws.",
        Button_link :<a href="https://www.geeksforgeeks.org/throw-throws-java/" class="button_lang">click</a>
    },
    {
    id: 44,
      
      name: "transient",
      meaning:
        " Java transient keyword is used in serialization. If you define any data member as transient, it will not be serialized.",
        Button_link :<a href="https://www.javatpoint.com/transient-keyword" class="button_lang">click</a>
    },
    {
    id: 45,
      
      name: "try",
      meaning:
        "Java try keyword is used to start a block of code that will be tested for exceptions. The try block must be followed by either catch or finally block.",
        Button_link :<a href="https://www.w3schools.com/java/ref_keyword_try.asp" class="button_lang">click</a>
    },
    {
    id: 46,
      
      name: "void",
      meaning:
        "Java void keyword is used to specify that a method does not have a return value.",
        Button_link :<a href="https://www.w3schools.com/java/ref_keyword_void.asp" class="button_lang">click</a>
    },
    {
    id: 47,
      
      name: "volatile",
      meaning:
        "Java volatile keyword is used to indicate that a variable may change asynchronously.",
        Button_link :<a href="https://www.javatpoint.com/volatile-keyword-in-java" class="button_lang">click</a>
    },
    {
    id: 48,
      
      name: "while",
      meaning:
        " Java while keyword is used to start a while loop. This loop iterates a part of the program several times. If the number of iteration is not fixed, it is recommended to use the while loop.",
        Button_link :<a href="https://www.w3schools.com/java/ref_keyword_while.asp" class="button_lang">click</a>
    }
  ];
  
  export default javalang;
  